"use strict";
const sentences = [
	"Am increasing at contrasted in favourable he considered astonished",
	"the valley of desire is filled with nothing but lies - my mother, who was clearly wrong",
	"Mrs chief great maids these which are ham match she",
	"Abide by the rules or get free hugs: your choice",
	"Doubtful disposed returned rejoiced to dashwood is so up",
	"Increasing impression interested expression he my at",
	"Respect invited request charmed me warrant to",
	"Expect no pretty as do though so genius afraid cousin",
	"Girl when of ye snug poor draw. Mistake totally of in chiefly",
	"Justice visitor him entered for. Continue delicate as unlocked entirely mr relation diverted in",
	"Known not end fully being style house. An whom down kept lain name so at easy",
	"I hate writing, except when its on this app",
	"Ferns need to take a chill pill or else",
	"Incommode necessary no it behaviour convinced distrusts an unfeeling he",
	"Could death since do we hoped is in. Exquisite no my attention extensive",
	"The determine conveying moonlight age",
	"Avoid marrying children for your own sake",
	"i'm honestly going to get arrested for being too cool",
	"Sitting so totally forbade hundred to",
	"She who arrival end how fertile enabled",
	"lööps bröther",
	"My mistake - I'm not stupid, just dumb",
	"Themselves at dispatched interested insensible am be prosperous reasonably it",
	"In either so spring wished",
	"Melancholy is honestly what fuels my relationships",
	"Mr, things do plenty others a great vanity of disbeleif",
	"Foods always perish. They taste best that way",
	"Performed suspicion in certainty so frankness by attention pretended",
	"Newspaper or in tolerably education enjoyment",
	"Extremity excellent certainty discourse sincerity no he so resembled",
	"Joy house worse arise total boy but",
	"Elderly people need to get their lives together, like just dont have osteoporosis",
	"People honestly need to calm down like your lives arent that bad",
	"Behaviour extremely her explained situation yet september gentleman are who",
	"Is a thought really a thought if it not thought by you?",
	"I wonder if you can call parks, that would be pretty insane, like \"hi yes can I reserve a spot in the park\"",
	"Why am I never invited to parties is never a question I have to ask myself. Especially today...",
	"Hear ye hear ye, yall are crazy",
	"you all need to get lives like i clearly have mine together, sitting here on a dumb clicker game",
	"Fifteen winding related may hearted colonel are way studied",
	"County suffer twenty or marked no moment in he. Meet shew or said like he",
	"Valley silent cannot things so remain oh to elinor",
	"Hunting is a scam - youre killing innocent bullets!",
	"Speaking numerous ask did horrible packages set",
	"Ashamed herself has distant can studied mrs",
	"i almost had a coherent  thought today. That was a close call!",
	"Perpetual darkness isnt that scary because eventually we would all realize that its just nap time for eternity",
	"i need someone to carry my around in a horse drawn carriage",
	"i dont understand geniuses like how can you be so smart but at the same time so dumb",
	"Barton waited twenty always repair in within we do",
	"im delightedly offended at the curiosity my aunt is dashing with BOTH salt and pepper",
	"Boy prosperous increasing surrounded companions her nor advantages sufficient put",
	"John on time down give meet help as of. Him waiting and correct believe now cottage she another",
	"Vexed six shy yet along learn maids her tiled. Through studied shyness evening bed him winding present",
	"Excuses, excuses. Hand over your garlic bread or else",
	"Do greatest at in learning steepest. Breakfast extremity suffering one who all otherwise suspected",
	"He at no nothing forbade up moments. Wholly uneasy at missed be of pretty whence",
	"John way sir high than law who week. Surrounded prosperous introduced it if is up dispatched",
	"Ferns are scary - i honestly think we need to eradicate them before they take over the world with their spores",
	"Put ladies design mrs sister was. Play on a hill, guys.",
	"Why would you play this dumb game instead of something productive",
	"Prosperous middletons is ye inhabiting as assistance me especially.",
	"I am at the stage of introvertedness where I dont even know if anyone else really exists",
	"going to bed is basically turning yourself off and back on again",
	"of iajewopifa howeih goahjweo ijdslkjlaksj dfjwepoiaj faoeiwjfoija",
];